/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.gui;

import Model.validations.UserDataValidations;
import javax.swing.*;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
/**
 *
 * @author gabrielheralv
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jLabelErrorNIF = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jTextFieldBirthDate = new javax.swing.JTextField();
        jLabelErrorBirthDate = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelErrorAge = new javax.swing.JLabel();
        jLabelZIP = new javax.swing.JLabel();
        jTextFieldZIP = new javax.swing.JTextField();
        jLabelErrorZIP = new javax.swing.JLabel();
        jButtonValidations = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 153));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("VALIDADOR DATOS USUARIOS");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Logo.png"))); // NOI18N

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelName.setText("Name:");
        jLabelName.setToolTipText("");

        jLabelErrorName.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorName.setToolTipText("");

        jLabelNIF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNIF.setText("NIF:");
        jLabelNIF.setToolTipText("");

        jLabelErrorNIF.setForeground(new java.awt.Color(255, 0, 0));

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("Email:");

        jLabelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBirthDate.setText("BirthDate:");

        jLabelErrorBirthDate.setForeground(new java.awt.Color(255, 0, 0));

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAge.setText("Age:");

        jTextFieldAge.setEditable(false);

        jLabelErrorAge.setForeground(new java.awt.Color(255, 0, 0));

        jLabelZIP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelZIP.setText("ZIP:");

        jLabelErrorZIP.setForeground(new java.awt.Color(255, 0, 0));

        jButtonValidations.setText("Validate");
        jButtonValidations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidationsActionPerformed(evt);
            }
        });

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabelLogo))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabelBirthDate)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorBirthDate))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabelAge)
                                .addGap(54, 54, 54)
                                .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorAge))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jButtonValidations)
                                        .addGap(57, 57, 57)
                                        .addComponent(jButtonClean)
                                        .addGap(46, 46, 46)
                                        .addComponent(jButtonCSV))
                                    .addGroup(jPanelMainLayout.createSequentialGroup()
                                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabelZIP)
                                                .addGap(54, 54, 54))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabelEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                            .addComponent(jTextFieldZIP))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrorZIP)
                                    .addComponent(jLabelErrorEmail)))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelName))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(jTextFieldName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelErrorName))))))
                .addGap(44, 44, 44))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorName))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNIF)
                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthDate)
                    .addComponent(jLabelErrorBirthDate))
                .addGap(28, 28, 28)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorAge))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZIP)
                    .addComponent(jTextFieldZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorZIP))
                .addGap(59, 59, 59)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidations)
                    .addComponent(jButtonClean)
                    .addComponent(jButtonCSV))
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidationsActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String birthdate = jTextFieldBirthDate.getText();
        String birth = jTextFieldBirthDate.getText();
        String PostalCode = jTextFieldZIP.getText();
        
        if (!UserDataValidations.checkName(name)){
            jLabelErrorName.setText("Incorrect name");
        }
        
        
        if (!UserDataValidations.checkId(nif)){
            jLabelErrorNIF.setText("Incorrect NIF");
        }
        
        
        if (!UserDataValidations.checkEmail(email)){
            jLabelErrorEmail.setText("Incorrect Email");
        }
        
         
        if(!UserDataValidations.checkFormatDate(birthdate)){
            jLabelErrorBirthDate.setText("Incorrect Birthdate");
        }
         
        if(!UserDataValidations.checkFormatDate(birth)){
            jLabelErrorBirthDate.setText("Incorrect Birth");
        }else{
            int edadInt = UserDataValidations.calculateAge(birth);
            String edad = String.valueOf(edadInt);
            jTextFieldAge.setText(edad);
            jTextFieldAge.setEditable(false);
            jLabelErrorBirthDate.setText("");
        }
        
     
        if (!UserDataValidations.postalCode(PostalCode)){
            jLabelErrorZIP.setText("Incorrect Postal Code");
        }
        if(UserDataValidations.postalCode(PostalCode) && UserDataValidations.checkFormatDate(birth)&& UserDataValidations.checkFormatDate(birthdate) && UserDataValidations.checkEmail(email) && UserDataValidations.checkId(nif) && UserDataValidations.checkName(name) ){
        jTextFieldName.setEditable(false);
        jTextFieldNIF.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldBirthDate.setEditable(false);
        jTextFieldAge.setEditable(false);
        jTextFieldZIP.setEditable(false);
        jButtonValidations.setEnabled(false);
        jButtonCSV.setEnabled(true);
        
        }
    }//GEN-LAST:event_jButtonValidationsActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        // TODO add your handling code here:
        jButtonValidations.setEnabled(true);
        jButtonClean.setEnabled(true);
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthDate.setText("");
        jTextFieldAge.setEditable(false);
        jTextFieldAge.setText("");
        jTextFieldZIP.setText("");
        jLabelErrorName.setText("");
        jLabelErrorNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelErrorBirthDate.setText("");
        jLabelErrorZIP.setText("");
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        // TODO add your handling code here:
        ClassFichero.writeFile(jTextFieldName.getText()+ ";" + jTextFieldNIF.getText()+ ";" + jTextFieldEmail.getText() + ";" + jTextFieldBirthDate.getText() + ";" + jTextFieldAge.getText() +";" + jTextFieldZIP.getText()+ "\n" );
        jButtonCSV.setEnabled(false);
    }//GEN-LAST:event_jButtonCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ClassFichero.createFile("user_data_GHA.csv");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonValidations;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorAge;
    private javax.swing.JLabel jLabelErrorBirthDate;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorNIF;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorZIP;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelZIP;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZIP;
    // End of variables declaration//GEN-END:variables
}
